#!/usr/bin/env python3
"""Embeds files in a C source as one string constant per file, plus a table.

Used by the Makefile to embed the Z runtime and the Z standard library in the
compiler, so a built `z` needs nothing else on disk to compile a program.

Each file becomes its own `static const char <prefix>_<n>[]`, and the tables
`<prefix>_names` and `<prefix>_srcs` pair them up, so the driver can lex each
file separately and stamp the right name on its tokens. Bytes outside printable
ASCII are emitted as three-digit octal escapes: the sources are arbitrary bytes
and must not be able to end the literal early, and octal has no ambiguity about
how many digits it takes the way \\x does.

A literal is wrapped into adjacent string fragments so no line runs past
WIDTH. C concatenates them, so the bytes are the same either way, and a
28KB standard library on one line is a line no `git diff` can show a change
on. The header is generated, so it is the one file in the tree whose diffs
have to be readable, and it is only readable if it is wrapped.
"""
import sys

# Longest output line, indent and quotes included.
WIDTH = 100


def c_bytes(data: bytes) -> str:
    out = []
    for b in data:
        if b == 0x22:
            out.append('\\"')
        elif b == 0x5C:
            out.append("\\\\")
        elif 0x20 <= b < 0x7F:
            out.append(chr(b))
        else:
            out.append("\\%03o" % b)
    return "".join(out)


def fragments(escaped: str, width: int) -> list:
    """Splits an escaped literal into chunks that each fit on one line.

    Breaks after the last space that fits, so a line ends at a word rather than
    mid-word. A run with no space in it -- a long identifier, a comment with its
    newlines escaped -- is cut at the width instead, which is the only thing that
    can be done to it. An escape sequence is never split: the cut points are
    chosen from the already-escaped text, so a `\\012` straddling the boundary
    cannot happen.
    """
    budget = width - len("    ") - 2  # indent, and the quotes on each side
    if budget < 1:
        raise ValueError("width %d is too narrow to hold any content" % width)
    out = []
    i = 0
    while i < len(escaped):
        chunk = escaped[i:i + budget]
        if i + budget < len(escaped):
            space = chunk.rfind(" ")
            if space != -1:
                chunk = chunk[:space + 1]
        out.append(chunk)
        i += len(chunk)
    return out


def main() -> int:
    prefix, paths = sys.argv[1], sys.argv[2:]
    if not paths:
        print("usage: embed.py <prefix> <file>...", file=sys.stderr)
        return 2
    print("/* generated by tools/embed.py -- do not edit */")
    for i, p in enumerate(paths):
        with open(p, "rb") as f:
            escaped = c_bytes(f.read())
        if not escaped:
            # Nothing to wrap, and an empty pair of fragments would be two lines
            # saying nothing.
            print('static const char %s_%d[] = "";' % (prefix, i))
            continue
        chunks = fragments(escaped, WIDTH)
        print("static const char %s_%d[] =" % (prefix, i))
        for n, chunk in enumerate(chunks):
            tail = ";" if n == len(chunks) - 1 else ""
            print('    "%s"%s' % (chunk, tail))
    print('static const char *const %s_names[] = {%s};'
          % (prefix, ", ".join('"%s"' % p for p in paths)))
    print("static const char *const %s_srcs[] = {%s};"
          % (prefix, ", ".join("%s_%d" % (prefix, i) for i in range(len(paths)))))
    print("#define %s_COUNT %d" % (prefix, len(paths)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
