#!/usr/bin/env python3
"""Embeds files in a C source as one string constant per file, plus a table.

Used by the Makefile to embed the Z runtime and the Z standard library in the
compiler, so a built `z` needs nothing else on disk to compile a program.

Each file becomes its own `static const char <prefix>_<n>[]`, and the tables
`<prefix>_names` and `<prefix>_srcs` pair them up, so the driver can lex each
file separately and stamp the right name on its tokens. Bytes outside printable
ASCII are emitted as three-digit octal escapes: the sources are arbitrary bytes
and must not be able to end the literal early, and octal has no ambiguity about
how many digits it takes the way \\x does.
"""
import sys


def c_bytes(data: bytes) -> str:
    out = []
    for b in data:
        if b == 0x22:
            out.append('\\"')
        elif b == 0x5C:
            out.append("\\\\")
        elif 0x20 <= b < 0x7F:
            out.append(chr(b))
        else:
            out.append("\\%03o" % b)
    return "".join(out)


def main() -> int:
    prefix, paths = sys.argv[1], sys.argv[2:]
    if not paths:
        print("usage: embed.py <prefix> <file>...", file=sys.stderr)
        return 2
    print("/* generated by tools/embed.py -- do not edit */")
    for i, p in enumerate(paths):
        with open(p, "rb") as f:
            print('static const char %s_%d[] = "%s";' % (prefix, i, c_bytes(f.read())))
    print('static const char *const %s_names[] = {%s};'
          % (prefix, ", ".join('"%s"' % p for p in paths)))
    print("static const char *const %s_srcs[] = {%s};"
          % (prefix, ", ".join("%s_%d" % (prefix, i) for i in range(len(paths)))))
    print("#define %s_COUNT %d" % (prefix, len(paths)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
