#define _POSIX_C_SOURCE 200809L

#include "arena.h"
#include "codegen.h"
#include "diag.h"
#include "lexer.h"
#include "parser.h"

#include "surface.h"

#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/wait.h>
#include <unistd.h>

/* Embedded copy of runtime/z_rt.c, generated by the Makefile. */
#include "runtime_src.h"

/* Embedded copy of the standard library's Z sources, generated by the Makefile.
 * They are lexed and spliced ahead of every compilation unit, so a program
 * gets `StringBuilder`, `Vec` and the rest without declaring anything. */
#include "std_src.h"

/* The virtual file name the standard library is lexed under. It is not a path
 * anyone can open -- the source is inside the compiler -- so a diagnostic that
 * lands in it says `z:std` rather than naming a file that does not exist. */
#define STD_SRC_NAME "z:std"

/* The compiler's own version, reported by `z --version`.
 *
 * A build is a C translation of this tree and nothing stamps it, so before this
 * the only honest answer to "which z is this" was to read the README and guess
 * from what it described. A release needs the artifact to name itself: a bug
 * report that cannot say what produced it cannot be reproduced.
 *
 * Hand-maintained and bumped with the tag, because the build has no other
 * source of truth -- the Makefile knows the C toolchain and not the release. */
#define Z_VERSION "0.11"

/* Reads an entire file into a NUL-terminated heap buffer. */
static char *read_file(const char *path, long *out_len) {
    FILE *f = fopen(path, "rb");
    if (f == NULL) {
        fprintf(stderr, "z: cannot open '%s'\n", path);
        return NULL;
    }
    fseek(f, 0, SEEK_END);
    long len = ftell(f);
    fseek(f, 0, SEEK_SET);
    if (len < 0) {
        fclose(f);
        return NULL;
    }
    char *buf = malloc((size_t)len + 1);
    if (buf == NULL) {
        fclose(f);
        fprintf(stderr, "z: out of memory reading '%s'\n", path);
        return NULL;
    }
    size_t got = fread(buf, 1, (size_t)len, f);
    fclose(f);
    buf[got] = '\0';
    *out_len = (long)got;
    return buf;
}

static int write_file(const char *path, const char *data) {
    /* `-` and /dev/stdout mean "write to stdout". */
    int to_stdout = strcmp(path, "-") == 0 || strcmp(path, "/dev/stdout") == 0;
    FILE *f = to_stdout ? stdout : fopen(path, "wb");
    if (f == NULL) {
        fprintf(stderr, "z: cannot write '%s'\n", path);
        return 0;
    }
    fputs(data, f);
    if (!to_stdout)
        fclose(f);
    else
        fflush(f);
    return 1;
}

/* Runs a program from an explicit argument vector, returning its exit status
 * (or -1 if it could not be started).
 *
 * Nothing here goes through a shell, and that is the whole point. The output
 * path and the caller's extra linker arguments are arbitrary text, so a shell
 * reads an apostrophe or a semicolon in either of them as syntax: `z build
 * main.z -o "x'; rm -rf ~; '"` used to end the quoted run at the apostrophe and
 * run whatever followed. An argv array has no grammar to get wrong, which
 * removes the whole class rather than asking each format string to escape
 * correctly. */
static int run_argv(char *const argv[]) {
    pid_t pid = fork();
    if (pid < 0)
        return -1;
    if (pid == 0) {
        execvp(argv[0], argv);
        /* Only reached when exec failed. 127 is what a shell reports for a
         * command it could not run, which is what this reported before. */
        fprintf(stderr, "z: cannot run '%s'\n", argv[0]);
        _exit(127);
    }
    int status = 0;
    while (waitpid(pid, &status, 0) < 0) {
        if (errno != EINTR)
            return -1;
    }
    if (WIFEXITED(status))
        return WEXITSTATUS(status);
    if (WIFSIGNALED(status))
        return 128 + WTERMSIG(status);
    return 1;
}

static void usage(void) {
    fprintf(stderr, "usage: z <run|build> <file.z> [-o output] [-O0..-O3] [--no-bounds] [-g]\n"
                    "       [-w] [-Werror] [-Wno-<name>] [--error-format=<fmt>] [--color=<when>]\n"
                    "       [--no-std] [--no-surface] [--surface=<path>] [linker args...]\n"
                    "       z --version\n"
                    "  --version print the compiler version and exit\n"
                    "  -O0 naive codegen (no register allocation, no folding)\n"
                    "  -O1 default: folding, register allocation, strength reduction\n"
                    "  -O2 adds loop-invariant code motion\n"
                    "  -O3 adds loop unrolling\n"
                    "  --no-bounds  drop the array and string index checks, which are on\n"
                    "               by default; measured and trusted code only\n"
                    "  -g        emit DWARF debug info (line table, functions, locals)\n"
                    "  -w         silence all warnings\n"
                    "  -Werror    treat warnings as errors\n"
                    "  -Wno-<name> silence one warning (unused-local, shadowed-local,\n"
                    "            unreachable, unused-import)\n"
                    "  --error-format=human|gcc|json  how to render diagnostics\n"
                    "  --color=auto|always|never       colour, auto = only on a terminal\n"
                    "  --no-std   compile without the embedded standard library\n"
                    "  --no-surface  ignore a project manifest; use the shipped names only\n"
                    "  --surface=<path>  take the dialect from this file instead of searching\n");
}

/* ---- imports ----
 *
 * `import "path.z";` splices the named file's tokens into this one, ahead of
 * the importing file's own, so its top-level declarations are visible exactly
 * as if the text had been pasted in -- which is what a program had to do by
 * hand before. Doing it on the token stream rather than by rewriting source
 * means the parser is unchanged, and every token keeps the Span (and therefore
 * the file name and line) it was lexed with, so a diagnostic in an imported
 * file points at that file.
 *
 * Paths resolve relative to the importing file's directory. Each file is
 * expanded at most once however many times it is imported, and a cycle is an
 * error rather than a hang.
 */

static void die_oom(void) {
    fprintf(stderr, "z: out of memory\n");
    exit(1);
}

static char *strdup_or_die(const char *s);

/* How many unrecognized arguments may be handed on to the link step. Far more
 * than any real link line needs, and a count rather than a byte budget, so a
 * long path cannot quietly eat the space an argument after it needs. */
#define MAX_LINK_ARGS 256

#define MAX_FILES 64
static const char *loaded_path[MAX_FILES];  /* paths already expanded (arena-owned) */
static const char *loading_path[MAX_FILES]; /* on the current expansion stack */
static int n_loaded = 0, n_loading = 0;

/* Directory part of `path`, as a fresh string ("." when there is none). */
static char *dir_of(const char *path) {
    const char *slash = strrchr(path, '/');
    if (slash == NULL)
        return strdup_or_die(".");
    size_t n = (size_t)(slash - path);
    if (n == 0)
        n = 1; /* "/foo.z" -> "/" */
    char *d = malloc(n + 1);
    if (d == NULL)
        die_oom();
    memcpy(d, path, n);
    d[n] = 0;
    return d;
}

/* Joins the importing file's directory with a relative import path. */
static char *resolve_import(const char *importer, const char *rel) {
    if (rel[0] == '/')
        return strdup_or_die(rel);
    char *dir = dir_of(importer);
    size_t need = strlen(dir) + 1 + strlen(rel) + 1;
    char *out = malloc(need);
    if (out == NULL)
        die_oom();
    snprintf(out, need, "%s/%s", dir, rel);
    free(dir);
    return out;
}

static char *strdup_or_die(const char *s) {
    size_t n = strlen(s) + 1;
    char *out = malloc(n);
    if (out == NULL)
        die_oom();
    memcpy(out, s, n);
    return out;
}

static int path_listed(const char **list, int n, const char *p) {
    for (int i = 0; i < n; i++)
        if (strcmp(list[i], p) == 0)
            return 1;
    return 0;
}

/* Expands `path`'s tokens, recursing into its imports. Appends the result to
 * `*out` / `*nout`, reallocating as needed. */
static int expand_file(Arena *arena, const char *path, Token **out, int *nout, int *capout,
                       StringTable *strings);

/* Appends one token, growing the output array. */
static void push_token(Arena *arena, Token **out, int *nout, int *capout, Token t) {
    if (*nout == *capout) {
        int ncap = *capout == 0 ? 64 : *capout * 2;
        Token *na = arena_alloc_array(arena, (size_t)ncap, sizeof(Token));
        if (*nout > 0)
            memcpy(na, *out, (size_t)*nout * sizeof(Token));
        *out = na;
        *capout = ncap;
    }
    (*out)[(*nout)++] = t;
}

static int expand_file(Arena *arena, const char *path, Token **out, int *nout, int *capout,
                       StringTable *strings) {
    /* The path is copied into the arena because every token's Span points at
     * it, and those spans are read long after this frame is gone. The strings
     * resolve_import hands back are freed by the caller, so using one directly
     * would leave the spans dangling -- and since malloc reuses the block, they
     * would all end up naming whichever path was allocated last. */
    char *stable = arena_strdup(arena, path);
    path = stable;
    if (n_loaded >= MAX_FILES || n_loading >= MAX_FILES) {
        fprintf(stderr, "z: too many imported files (limit %d)\n", MAX_FILES);
        return 1;
    }
    if (path_listed(loaded_path, n_loaded, path))
        return 0; /* already in the unit; a second import is a no-op */
    if (path_listed(loading_path, n_loading, path)) {
        fprintf(stderr, "z: import cycle: %s imports itself, directly or indirectly\n", path);
        return 1;
    }
    loading_path[n_loading++] = path; /* arena-owned */

    long len = 0;
    char *text = read_file(path, &len); /* reports the open failure itself */
    if (text == NULL) {
        n_loading--;
        return 1;
    }
    /* Keep the text in the arena: diagnostics render an excerpt from it long
     * after lexing, so freeing the read buffer here would leave them pointing
     * at freed memory. arena_free then cleans up every imported file at once. */
    char *kept = arena_alloc_array(arena, (size_t)len + 1, 1);
    memcpy(kept, text, (size_t)len);
    kept[len] = 0;
    free(text);
    text = kept;
    diag_set_source(path, text);

    int ntoks = 0;
    Token *toks = lex_all_file(arena, text, (int)len, strings, &ntoks, path);
    if (diag_error_count() > 0) {
        n_loading--;
        return 1;
    }

    /* Walk the tokens, recursing at each top-level `import "..." ;` and
     * otherwise copying them through. */
    int depth = 0;
    for (int i = 0; i < ntoks; i++) {
        Token *t = &toks[i];
        if (t->kind == T_LBRACE) {
            depth++;
            push_token(arena, out, nout, capout, *t);
            continue;
        }
        if (t->kind == T_RBRACE) {
            depth--;
            push_token(arena, out, nout, capout, *t);
            continue;
        }
        /* lex_all terminates each file with T_EOF, and the parser stops at the
         * first one, so the per-file sentinels are dropped here; a single one
         * is appended after the whole unit is assembled. */
        if (t->kind == T_EOF)
            continue;
        if (depth == 0 && t->kind == T_KW_IMPORT) {
            if (i + 2 >= ntoks || toks[i + 1].kind != T_STRING || toks[i + 2].kind != T_SEMI) {
                fprintf(stderr, "%s:%d:%d: error: expected `import \"file.z\";`\n",
                        t->span.file ? t->span.file : path, t->span.line, t->span.col);
                n_loading--;
                return 1;
            }
            char *rel = strings->items[toks[i + 1].str_id];
            char *target = resolve_import(path, rel);
            if (expand_file(arena, target, out, nout, capout, strings) != 0) {
                free(target);
                n_loading--;
                return 1;
            }
            free(target);
            /* Step over the string and the semicolon; the loop's own i++ then
             * lands on whatever follows the statement. */
            i += 2;
            continue;
        }
        push_token(arena, out, nout, capout, *t);
    }

    n_loading--;
    if (n_loaded < MAX_FILES)
        loaded_path[n_loaded++] = path; /* arena-owned, freed with the arena */
    return 0;
}

/* Lexes the embedded standard library and appends its tokens to `out`.
 *
 * Ahead of the program's own tokens, so its declarations are in scope
 * everywhere: at the top level, inside a function, inside a class. Each file is
 * lexed on its own and its tokens stamped with its own name, so a diagnostic
 * inside the library names the file a reader can go and read -- and a line
 * number that counts within that file rather than across all of them.
 *
 * The name is the path the file had when it was embedded, which is not a path
 * anyone can open. That is honest: the source is inside the compiler, and saying
 * so beats naming a file that does not exist.
 *
 * Returns 0 on success. */
static int expand_stdlib(Arena *arena, Token **out, int *nout, int *capout, StringTable *strings) {
    for (int f = 0; f < std_src_COUNT; f++) {
        const char *src = std_src_srcs[f];
        const char *path = arena_strdup(arena, std_src_names[f]);
        diag_set_source(path, src);
        int ntoks = 0;
        Token *toks = lex_all_file(arena, src, (int)strlen(src), strings, &ntoks, path);
        if (diag_error_count() > 0) {
            fprintf(stderr, "z: the embedded standard library does not compile\n");
            return 1;
        }
        for (int i = 0; i < ntoks; i++) {
            /* The per-file terminator is dropped; one is appended after the whole
             * unit is assembled, and the parser stops at the first one it sees. */
            if (toks[i].kind != T_EOF)
                push_token(arena, out, nout, capout, toks[i]);
        }
    }
    return 0;
}

/* Compiles `src` and either writes assembly (asm_path != NULL) or assembles +
 * links an executable. Returns the process exit status. */
static int compile(const char *src, const char *exe, const char *asm_path, int bounds_checks,
                   int opt_level, int debug_info, int use_stdlib, int no_surface,
                   const char *surface_path, char *const *link_args, int n_link_args) {
    long len = 0;
    char *text = read_file(src, &len);
    if (text == NULL)
        return 1;

    Arena arena;
    arena_init(&arena);
    diag_set_source(src, text);

    StringTable strings;
    string_table_init(&strings, &arena);

    /* The standard library first, then `import`s, then the program: the library
     * is in scope in the library's own importers, and the root file is just
     * another file to the expander, so imports nest to any depth. */
    int ntoks = 0, tcap = 0;
    Token *toks = NULL;
    if (use_stdlib && expand_stdlib(&arena, &toks, &ntoks, &tcap, &strings) != 0) {
        arena_free(&arena);
        free(text);
        return 1;
    }
    if (expand_file(&arena, src, &toks, &ntoks, &tcap, &strings) != 0 || diag_error_count() > 0) {
        arena_free(&arena);
        free(text);
        return 1;
    }
    /* One terminator for the assembled unit.
     *
     * It inherits the last real token's position rather than being zeroed, because
     * a diagnostic whose expected token is the end of the file is reported at this
     * token's span, and a zeroed span prints as `0:0` and quotes the file's first
     * line. That is how a missing `;` at the end of the last line came to be
     * reported on line 1, pointing at a comment that had nothing to do with it.
     *
     * Pointing at the last token rather than one byte past it is also the more
     * useful answer: "expected ';' but found end of file" wants to show the token
     * the semicolon should have followed. */
    if (ntoks == tcap) {
        Token *bigger = arena_alloc_array(&arena, ntoks + 1, sizeof(Token));
        if (ntoks > 0)
            memcpy(bigger, toks, (size_t)ntoks * sizeof(Token));
        toks = bigger;
    }
    memset(&toks[ntoks], 0, sizeof toks[ntoks]);
    if (ntoks > 0) {
        toks[ntoks] = toks[ntoks - 1];
        toks[ntoks].kind = T_EOF;
        toks[ntoks].span.len = 0;
    } else {
        toks[ntoks].kind = T_EOF;
        toks[ntoks].span.file = src;
        toks[ntoks].span.line = 1;
        toks[ntoks].span.col = 1;
    }
    ntoks++;

    /* The dialect this program is written in. Loaded from the manifest that
     * governs `src`, unless the caller turned that off or named one. The surface
     * is on the arena because the parser keeps a pointer to it and shallow copies
     * of the parser share that pointer. */
    Surface *surf = surface_new(&arena);
    if (surf == NULL)
        return 1;
    if (no_surface) {
        /* Asked to ignore the manifest. The shipped names still apply, because
         * they are the language rather than a project's choice. */
    } else if (surface_path != NULL) {
        if (surface_load(surf, surface_path) != 0)
            return 1;
    } else if (surface_discover(surf, src) < 0) {
        return 1;
    }

    Stmt *program = parse_program(&arena, toks, ntoks, &strings, opt_level, surf);
    /* A summary line, because "there were 3 of those somewhere above" is the
     * one thing a reader cannot work out by scrolling. Skipped in the
     * machine-readable formats, where a line that is not a diagnostic would be
     * a line a parser has to know to ignore. */
    if (diag_get_format() == DIAG_FMT_HUMAN && diag_warning_count() > 0)
        fprintf(stderr, "%d warning%s emitted.\n", diag_warning_count(),
                diag_warning_count() == 1 ? "" : "s");
    if (diag_error_count() > 0) {
        arena_free(&arena);
        free(text);
        return 1;
    }

    CodegenOptions copt;
    copt.bounds_checks = bounds_checks;
    copt.debug_info = debug_info;
    copt.opt_level = opt_level;
    char *asm_text = codegen_emit_opts(&arena, program, &strings, &copt);

    if (asm_path != NULL) {
        write_file(asm_path, asm_text);
        free(asm_text);
        arena_free(&arena);
        free(text);
        return 0;
    }

    char default_asm[256];
    if (asm_path == NULL) {
        snprintf(default_asm, sizeof default_asm, "/tmp/z_%ld.s", (long)getpid());
    }
    const char *apath = asm_path != NULL ? asm_path : default_asm;
    if (!write_file(apath, asm_text)) {
        free(asm_text);
        arena_free(&arena);
        free(text);
        return 1;
    }

    int status = 0;
    if (exe != NULL) {
        /* Write the embedded runtime and link it with the generated assembly. */
        char rt_path[256];
        snprintf(rt_path, sizeof rt_path, "/tmp/z_%ld_rt.c", (long)getpid());
        FILE *rtf = fopen(rt_path, "wb");
        if (rtf == NULL) {
            fprintf(stderr, "z: cannot write runtime source\n");
            remove(apath);
            free(asm_text);
            arena_free(&arena);
            free(text);
            return 1;
        }
        fwrite(runtime_src_0, 1, strlen(runtime_src_0), rtf);
        fclose(rtf);
        /* Anything the caller passed after the source file is handed straight
         * to the linker, so `z build main.z -o main -lm -L/opt/lib` works and an
         * extern symbol can be satisfied by a plain .c or .o path. Each one
         * becomes one argv entry, so a path with a space or a quote in it
         * survives without being quoted, escaped or truncated. */
        char *argv[6 + MAX_LINK_ARGS + 1];
        int n = 0;
        argv[n++] = (char *)"cc";
        argv[n++] = (char *)"-no-pie";
        argv[n++] = (char *)"-o";
        argv[n++] = (char *)exe;
        argv[n++] = (char *)apath;
        argv[n++] = (char *)rt_path;
        for (int i = 0; i < n_link_args; i++)
            argv[n++] = link_args[i];
        argv[n] = NULL;
        status = run_argv(argv);
        remove(rt_path);
        if (status != 0)
            fprintf(stderr, "z: assembling/linking failed\n");
    } else {
        char obj_path[256];
        snprintf(obj_path, sizeof obj_path, "/tmp/z_%ld.o", (long)getpid());
        char *argv[] = {(char *)"cc", (char *)"-c", (char *)"-o", obj_path, (char *)apath, NULL};
        status = run_argv(argv);
        remove(obj_path);
    }

    remove(apath);
    free(asm_text);
    arena_free(&arena);
    free(text);
    return status;
}

int main(int argc, char **argv) {
    /* `--version` is answered before anything is parsed, and before the
     * argument count is checked, because it takes no file and is the one
     * invocation that must work with nothing else on the line. Anything left
     * over is ignored rather than diagnosed: a build script that runs
     * `z --version` to capture the version and has already appended its own
     * flags should get the number, not a usage error. */
    if (argc >= 2 && strcmp(argv[1], "--version") == 0) {
        printf("z %s\n", Z_VERSION);
        return 0;
    }
    if (argc < 3) {
        usage();
        return 2;
    }
    const char *cmd = argv[1];
    const char *src = argv[2];
    const char *out = NULL;
    /* Bounds checks are on unless `--no-bounds` says otherwise.
     *
     * An unchecked read is faster, and that is the whole argument for having had
     * this behind a flag. It is the wrong default for a language whose array is
     * a bare pointer with a length header in front of it: the check is one
     * compare against a value that is already in a register, and the alternative
     * to paying it is a program that reads whatever the next allocation put
     * there. `--no-bounds` is still there for the code that has been measured
     * and is trusted, and it is a real flag now rather than one that fell through
     * to the C compiler. */
    int bounds_checks = 1;
    int debug_info = 0;
    /* The embedded standard library is on by default; --no-std turns it off,
     * which is what a program that wants to define its own `StringBuilder` (or
     * measure the compiler without the library in the way) needs. */
    int use_stdlib = 1;
    /* --no-surface ignores a project manifest; --surface=<path> names one
     * explicitly. Both exist because a manifest is found by walking up from the
     * source, which is convenient until a build runs somewhere it should not. */
    int no_surface = 0;
    const char *surface_path = NULL;
    /* -O0..-O3, spelled like gcc's. The default matches what the compiler has
     * always done, so an invocation without a flag behaves exactly as before. */
    int opt_level = Z_OPT_DEFAULT;
    /* Everything the compiler does not recognize is collected verbatim and
     * handed to the link step. These are the caller's own pointers rather than
     * copies, so there is no fixed buffer to overflow and no length at which an
     * argument starts being dropped without a word. The count is still bounded,
     * and the bound is reported rather than silently truncating the list. */
    char *link_args[MAX_LINK_ARGS];
    int n_link_args = 0;
    for (int i = 3; i < argc; i++) {
        if (strcmp(argv[i], "-o") == 0 && i + 1 < argc) {
            out = argv[++i];
        } else if (strcmp(argv[i], "--bounds") == 0) {
            /* The default. Still accepted, so a script that passes it explicitly
             * keeps working and keeps meaning what it says. */
            bounds_checks = 1;
        } else if (strcmp(argv[i], "--no-bounds") == 0) {
            /* Consumed here rather than collected for the link step. It used to
             * fall through to `cc`, which does not have a `-fno-bounds` for C and
             * says so: "valid for Modula-2 but not for C". Every build that asked
             * for no bounds therefore printed a warning from a tool the caller
             * never named, which is a warning nobody can act on. */
            bounds_checks = 0;
        } else if (strcmp(argv[i], "--no-std") == 0) {
            use_stdlib = 0;
        } else if (strcmp(argv[i], "--no-surface") == 0) {
            no_surface = 1;
        } else if (strncmp(argv[i], "--surface=", 10) == 0) {
            surface_path = argv[i] + 10;
        } else if (strcmp(argv[i], "-g") == 0) {
            /* Consumed here rather than passed to the link: the debug sections
             * are produced by codegen emitting .loc and .debug_* directives, and
             * forwarding -g would only ask the C toolchain for debug info about
             * code it did not compile. */
            debug_info = 1;
        } else if (diag_set_warn_flag(argv[i])) {
            /* A warning flag we know. Anything else beginning -W falls through
             * to the linker untouched, as it always has. */
        } else if (strncmp(argv[i], "--error-format=", 15) == 0) {
            if (!diag_set_format_flag(argv[i] + 15)) {
                fprintf(stderr, "z: unknown --error-format '%s' (human, gcc, json)\n",
                        argv[i] + 15);
                return 2;
            }
        } else if (strncmp(argv[i], "--color=", 8) == 0) {
            if (!diag_set_color_flag(argv[i] + 8)) {
                fprintf(stderr, "z: unknown --color '%s' (auto, always, never)\n", argv[i] + 8);
                return 2;
            }
        } else if (strncmp(argv[i], "-O", 2) == 0 && argv[i][2] >= '0' && argv[i][2] <= '9' &&
                   argv[i][3] == 0) {
            /* -O0..-O3. Anything else starting -O is not ours, so it falls
             * through to the linker untouched. */
            opt_level = argv[i][2] - '0';
        } else if (n_link_args == MAX_LINK_ARGS) {
            fprintf(stderr, "z: at most %d linker arguments, and %d were given\n", MAX_LINK_ARGS,
                    n_link_args + 1);
            return 2;
        } else {
            link_args[n_link_args++] = argv[i];
        }
    }

    if (strcmp(cmd, "build") == 0) {
        char *default_out = NULL;
        if (out == NULL) {
            const char *base = strrchr(src, '/');
            base = base ? base + 1 : src;
            size_t need = strlen(base) + 8;
            default_out = malloc(need);
            if (default_out == NULL) {
                fprintf(stderr, "z: out of memory\n");
                return 1;
            }
            snprintf(default_out, need, "./%s", base);
            char *dot = strrchr(default_out, '.');
            if (dot != NULL)
                *dot = '\0';
            out = default_out;
        }
        int rc = compile(src, out, NULL, bounds_checks, opt_level, debug_info, use_stdlib,
                         no_surface, surface_path, link_args, n_link_args) == 0
                     ? 0
                     : 1;
        free(default_out);
        return rc;
    }

    if (strcmp(cmd, "run") == 0) {
        char exe[256];
        snprintf(exe, sizeof exe, "/tmp/z_%ld.out", (long)getpid());
        if (compile(src, exe, NULL, bounds_checks, opt_level, debug_info, use_stdlib, no_surface,
                    surface_path, link_args, n_link_args) != 0)
            return 1;
        char *run_it[] = {exe, NULL};
        int rc = run_argv(run_it);
        remove(exe);
        return rc;
    }

    if (strcmp(cmd, "asm") == 0) {
        /* Debugging aid: emit the generated assembly to stdout. */
        return compile(src, NULL, "/dev/stdout", bounds_checks, opt_level, debug_info, use_stdlib,
                       no_surface, surface_path, link_args, n_link_args) == 0
                   ? 0
                   : 1;
    }

    usage();
    return 2;
}
