#define _POSIX_C_SOURCE 200809L

#include "arena.h"
#include "codegen.h"
#include "diag.h"
#include "lexer.h"
#include "parser.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/wait.h>
#include <unistd.h>

/* Embedded copy of runtime/vela_rt.c, generated by the Makefile. */
#include "runtime_src.h"

/* Reads an entire file into a NUL-terminated heap buffer. */
static char *read_file(const char *path, long *out_len) {
    FILE *f = fopen(path, "rb");
    if (f == NULL) {
        fprintf(stderr, "z: cannot open '%s'\n", path);
        return NULL;
    }
    fseek(f, 0, SEEK_END);
    long len = ftell(f);
    fseek(f, 0, SEEK_SET);
    if (len < 0) {
        fclose(f);
        return NULL;
    }
    char *buf = malloc((size_t)len + 1);
    if (buf == NULL) {
        fclose(f);
        fprintf(stderr, "z: out of memory reading '%s'\n", path);
        return NULL;
    }
    size_t got = fread(buf, 1, (size_t)len, f);
    fclose(f);
    buf[got] = '\0';
    *out_len = (long)got;
    return buf;
}

static int write_file(const char *path, const char *data) {
    /* `-` and /dev/stdout mean "write to stdout". */
    int to_stdout = strcmp(path, "-") == 0 || strcmp(path, "/dev/stdout") == 0;
    FILE *f = to_stdout ? stdout : fopen(path, "wb");
    if (f == NULL) {
        fprintf(stderr, "z: cannot write '%s'\n", path);
        return 0;
    }
    fputs(data, f);
    if (!to_stdout)
        fclose(f);
    else
        fflush(f);
    return 1;
}

/* Runs a command, returning its exit status (or -1 on spawn failure). */
static int run_command(const char *cmd) {
    int rc = system(cmd);
    if (rc == -1)
        return -1;
    if (WIFEXITED(rc))
        return WEXITSTATUS(rc);
    return 1;
}

static void usage(void) { fprintf(stderr, "usage: z <run|build> <file.z> [-o output]\n"); }

/* Compiles `src` and either writes assembly (asm_path != NULL) or assembles +
 * links an executable. Returns the process exit status. */
static int compile(const char *src, const char *exe, const char *asm_path) {
    long len = 0;
    char *text = read_file(src, &len);
    if (text == NULL)
        return 1;

    Arena arena;
    arena_init(&arena);
    diag_set_source(src, text);

    StringTable strings;
    string_table_init(&strings, &arena);

    int ntoks = 0;
    Token *toks = lex_all(&arena, text, (int)len, &strings, &ntoks);
    if (diag_error_count() > 0) {
        arena_free(&arena);
        free(text);
        return 1;
    }

    Stmt *program = parse_program(&arena, toks, ntoks, &strings);
    if (diag_error_count() > 0) {
        arena_free(&arena);
        free(text);
        return 1;
    }

    char *asm_text = codegen_emit(&arena, program, &strings);

    if (asm_path != NULL) {
        write_file(asm_path, asm_text);
        free(asm_text);
        arena_free(&arena);
        free(text);
        return 0;
    }

    char default_asm[256];
    if (asm_path == NULL) {
        snprintf(default_asm, sizeof default_asm, "/tmp/z_%ld.s", (long)getpid());
    }
    const char *apath = asm_path != NULL ? asm_path : default_asm;
    if (!write_file(apath, asm_text)) {
        free(asm_text);
        arena_free(&arena);
        free(text);
        return 1;
    }

    int status = 0;
    if (exe != NULL) {
        /* Write the embedded runtime and link it with the generated assembly. */
        char rt_path[256];
        snprintf(rt_path, sizeof rt_path, "/tmp/z_%ld_rt.c", (long)getpid());
        FILE *rtf = fopen(rt_path, "wb");
        if (rtf == NULL) {
            fprintf(stderr, "z: cannot write runtime source\n");
            remove(apath);
            free(asm_text);
            arena_free(&arena);
            free(text);
            return 1;
        }
        fwrite(runtime_src, 1, strlen(runtime_src), rtf);
        fclose(rtf);
        char cmd[1400];
        snprintf(cmd, sizeof cmd, "cc -no-pie -o '%s' '%s' '%s' 2>&1", exe, apath, rt_path);
        status = run_command(cmd);
        remove(rt_path);
        if (status != 0)
            fprintf(stderr, "z: assembling/linking failed\n");
    } else {
        char cmd[1024];
        snprintf(cmd, sizeof cmd, "cc -c -o '/tmp/z_%ld.o' '%s' 2>&1", (long)getpid(), apath);
        status = run_command(cmd);
    }

    remove(apath);
    free(asm_text);
    arena_free(&arena);
    free(text);
    return status;
}

int main(int argc, char **argv) {
    if (argc < 3) {
        usage();
        return 2;
    }
    const char *cmd = argv[1];
    const char *src = argv[2];
    const char *out = NULL;
    for (int i = 3; i < argc; i++) {
        if (strcmp(argv[i], "-o") == 0 && i + 1 < argc) {
            out = argv[++i];
        }
    }

    if (strcmp(cmd, "build") == 0) {
        char *default_out = NULL;
        if (out == NULL) {
            const char *base = strrchr(src, '/');
            base = base ? base + 1 : src;
            size_t need = strlen(base) + 8;
            default_out = malloc(need);
            if (default_out == NULL) {
                fprintf(stderr, "z: out of memory\n");
                return 1;
            }
            snprintf(default_out, need, "./%s", base);
            char *dot = strrchr(default_out, '.');
            if (dot != NULL)
                *dot = '\0';
            out = default_out;
        }
        int rc = compile(src, out, NULL) == 0 ? 0 : 1;
        free(default_out);
        return rc;
    }

    if (strcmp(cmd, "run") == 0) {
        char exe[256];
        snprintf(exe, sizeof exe, "/tmp/z_%ld.out", (long)getpid());
        if (compile(src, exe, NULL) != 0)
            return 1;
        char run_cmd[512];
        snprintf(run_cmd, sizeof run_cmd, "'%s'", exe);
        int rc = run_command(run_cmd);
        remove(exe);
        return rc;
    }

    if (strcmp(cmd, "asm") == 0) {
        /* Debugging aid: emit the generated assembly to stdout. */
        return compile(src, NULL, "/dev/stdout") == 0 ? 0 : 1;
    }

    usage();
    return 2;
}
