#include "token.h"

const char *token_kind_name(TokenKind kind) {
    switch (kind) {
    case T_EOF:
        return "end of file";
    case T_IDENT:
        return "identifier";
    case T_INT:
        return "integer literal";
    case T_F64:
        return "float literal";
    case T_STRING:
        return "string literal";
    case T_INTERP:
        return "interpolated string";
    case T_KW_INT:
        return "'int'";
    case T_KW_BOOL:
        return "'bool'";
    case T_KW_FLOAT:
        return "'float'";
    case T_KW_CLOSURE:
        return "'closure'";
    case T_KW_STRING:
        return "'string'";
    case T_KW_VOID:
        return "'void'";
    case T_KW_VAR: /* `var` or `auto`; the lexer maps both to this one kind. */
        return "'var'";
    case T_KW_CONST:
        return "'const'";
    case T_KW_BREAK:
        return "'break'";
    case T_KW_CONTINUE:
        return "'continue'";
    case T_KW_IF:
        return "'if'";
    case T_KW_ELSE:
        return "'else'";
    case T_KW_WHILE:
        return "'while'";
    case T_KW_FOR:
        return "'for'";
    case T_KW_FOREACH:
        return "'foreach'";
    case T_KW_IN:
        return "'in'";
    case T_KW_NEW:
        return "'new'";
    case T_KW_STRUCT:
        return "'struct'";
    case T_KW_ENUM:
        return "'enum'";
    case T_KW_CLASS:
        return "'class'";
    case T_KW_INTERFACE:
        return "'interface'";
    case T_KW_VIRTUAL:
        return "'virtual'";
    case T_KW_OVERRIDE:
        return "'override'";
    case T_KW_MATCH:
        return "'match'";
    case T_KW_THIS:
        return "'this'";
    case T_LBRACKET:
        return "'['";
    case T_RBRACKET:
        return "']'";
    case T_DOT:
        return "'.'";
    case T_DOTDOT:
        return "'..'";
    case T_QUESTION:
        return "'?'";
    case T_COLON:
        return "':'";
    case T_ARROW:
        return "->";
    case T_FATARROW:
        return "'=>'";
    case T_KW_RETURN:
        return "'return'";
    case T_KW_IMPORT:
        return "import";
    case T_KW_METHOD:
        return "method";
    case T_KW_FN:
        return "fn";
    case T_KW_EXPORT:
        return "export";
    case T_KW_EXTERN:
        return "extern";
    case T_KW_NULL:
        return "null";
    case T_KW_TRUE:
        return "'true'";
    case T_KW_FALSE:
        return "'false'";
    case T_LPAREN:
        return "'('";
    case T_RPAREN:
        return "')'";
    case T_LBRACE:
        return "'{'";
    case T_RBRACE:
        return "'}'";
    case T_SEMI:
        return "';'";
    case T_COMMA:
        return "','";
    case T_PLUS:
        return "'+'";
    case T_MINUS:
        return "'-'";
    case T_STAR:
        return "'*'";
    case T_SLASH:
        return "'/'";
    case T_PERCENT:
        return "'%'";
    case T_ASSIGN:
        return "'='";
    case T_EQ:
        return "'=='";
    case T_NE:
        return "'!='";
    case T_LT:
        return "'<'";
    case T_LE:
        return "'<='";
    case T_GT:
        return "'>'";
    case T_GE:
        return "'>='";
    case T_NOT:
        return "'!'";
    case T_AMP:
        return "'&'";
    case T_AND:
        return "'&&'";
    case T_OR:
        return "'||'";
    case T_PLUS_EQ:
        return "'+='";
    case T_MINUS_EQ:
        return "'-='";
    case T_STAR_EQ:
        return "'*='";
    case T_SLASH_EQ:
        return "'/='";
    case T_PERCENT_EQ:
        return "'%='";
    case T_PLUSPLUS:
        return "'++'";
    case T_MINUSMINUS:
        return "'--'";
    case T_PIPE:
        return "'|'";
    case T_CARET:
        return "'^'";
    case T_TILDE:
        return "'~'";
    case T_SHL:
        return "'<<'";
    case T_SHR:
        return "'>>'";
    case T_AMP_EQ:
        return "'&='";
    case T_PIPE_EQ:
        return "'|='";
    case T_CARET_EQ:
        return "'^='";
    case T_SHL_EQ:
        return "'<<='";
    case T_SHR_EQ:
        return "'>>='";
    }
    return "token";
}
